name: Manual Release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Release Type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  manual-release:
    name: Create Manual Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create Release Branch
        run: |
          git checkout -b release/manual-release-${{ github.run_id }}
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Get Latest Release
        id: latest_release
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT
          
      - name: Generate Changelog
        id: changelog
        run: |
          changelog=$(git log ${{ steps.latest_release.outputs.latest_tag }}..HEAD --pretty=format:"%s (%h)" | sed 's/^/- /')
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$changelog" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: prepare release ${{ github.event.inputs.releaseType }}"
          title: "chore: prepare release ${{ github.event.inputs.releaseType }}"
          body: |
            This PR was automatically created by the manual release workflow.
            
            Changes since ${{ steps.latest_release.outputs.latest_tag }}:
            ${{ steps.changelog.outputs.changelog }}
          branch: release/manual-release-${{ github.run_id }}
          base: main
          labels: release
